[[feeds.feedlist]]
link = "https://www.contretemps.eu/rss"
domain = "contretemps.eu"
title = "Contretemps"
image = "https://www.contretemps.eu/wp-content/uploads/ctt.ico"
[[feeds.feedlist]]
title = "Spectre"
link = "https://spectremedia.org/feed/podcast/"
domain = "spectremedia.org"
image = "https://spectremedia.org/wp-content/themes/spectre-v2/favicon.png"
[[feeds.feedlist]]
title="L'Insoumission"
link = "https://linsoumission.fr/feed/"
domain = "linsoumission.fr"
image = "https://linsoumission.fr/wp-content/uploads/2025/02/cropped-Pharefavicon-32x32.png"
[[feeds.feedlist]]
link = "https://melenchon.fr/feed/"
domain = "melenchon.fr"
title = "JLM Le blog"
image = "https://melenchon.fr/wp-content/uploads/2024/10/cropped-turtle2-32x32.png"
[[feeds.feedlist]]
title = "Afrique XXI"
link = "https://afriquexxi.info/?page=backend&lang=fr"
domain = "afriquexxi.info"
image = "https://afriquexxi.info/squelettes-2021/favicon/favicon-32x32.png"
[[feeds.feedlist]]
title = "Frustration Magazine"
link = "https://www.frustrationmagazine.fr/feed.xml"
domain = "frustrationmagazine.fr"
image = "https://frustrationmagazine.fr/img/favicon_light.png"
[[feeds.feedlist]]
title = "Ballast"
link = "https://www.revue-ballast.fr/feed/"
domain = "revue-ballast.fr"
image = "https://www.revue-ballast.fr/wp-content/uploads/2016/09/ballast_favicon.ico"
[[feeds.feedlist]]
title = "Orient XXI"
link = "https://orientxxi.info/?page=backend&lang=fr"
domain = "orientxxi.info"
image = "https://orientxxi.info/squelettes-2021/favicon/android-icon-192x192.png"
[[feeds.feedlist]]
title = "Survie"
link = "https://survie.org/spip.php?page=backend"
domain = "survie.org"
image = "https://survie.org/favicon.ico"
[[feeds.feedlist]]
title = "Révolution Permanente"
link = "https://www.revolutionpermanente.fr/spip.php?page=backend&id_mot=5"
domain = "revolutionpermanente.fr"
image = "https://pbs.twimg.com/profile_images/1584923031687806980/SgoWFAk9_400x400.jpg"
[[feeds.feedlist]]
link = "https://backend.streetpress.com/rss.xml"
title = "StreetPress"
domain = "streetpress.com"
image = "https://www.streetpress.com/favicon.ico"
[[feeds.feedlist]]
link = "https://strass-syndicat.org/feed/"
domain = "strass-syndicat.org"
title = "Le STRASS"
image = "https://strass-syndicat.org/wp-content/uploads/2020/04/cropped-fav-strass-32x32.png"
[[feeds.feedlist]]
link = "https://lafranceinsoumise.fr/feed/"
domain = "lafranceinsoumise.fr"
title = "LFI"
image = "https://lafranceinsoumise.fr/wp-content/uploads/2024/11/cropped-TOUT-PETIT-LOGO-32x32.png"
[[feeds.feedlist]]
link = "https://leftalliance.eu/feed/"
domain = "leftalliance.eu"
title = "EU LEFT Alliance"
image = "https://leftalliance.eu/wp-content/uploads/2025/04/cropped-FAVICON-ELA-1-32x32.png"
[[feeds.feedlist]]
link = "https://institutlaboetie.fr/feed/"
domain = "institutlaboetie.fr"
title = "Institut La Boétie"
image = "https://institutlaboetie.fr/wp-content/uploads/2020/03/LOGO-FAVICON-150x150.png"
[[feeds.feedlist]]
link = "https://api.arretsurimages.net/api/public/rss/all-content"
domain = "arretsurimages.net"
title = "Arrêt sur Images"
image = "https://www.arretsurimages.net/assets/img/favicon/favicon-32x32.png"
[[feeds.feedlist]]
link = "https://infos-ouvrieres.fr/feed/"
domain = "infos-ouvrieres.fr"
title = "Informations Ouvrières"
image = "https://infos-ouvrieres.fr/wp-content/uploads/2018/12/Logo-500x500-e1612179565960-92x92.png"
[[feeds.feedlist]]
link = "https://www.acrimed.org/spip.php?page=backend"
domain = "acrimed.org"
title = "Acrimed"
image = "https://www.acrimed.org/squelettes/favicon.ico"
[[feeds.feedlist]]
link = "https://www.revue-ouvrage.org/feed/"
domain = "revue-ouvrage.org"
title = "Ouvrage"
image = "https://www.revue-ouvrage.org/wp-content/uploads/2020/04/cropped-ouvrage-noir-1-32x32.png"
[[feeds.feedlist]]
link = "https://www.socialter.fr/rss"
domain = "socialter.fr"
title = "Socialter"
subtitle = "Critique radicale et alternatives"
image = "https://www.socialter.fr/theme/images/favicon.png"
[[feeds.feedlist]]
link = "https://basta.media/spip.php?page=backend"
domain = "basta.media"
title = "Basta!"
image = "https://portail.basta.media/local/favicon/basta-media-332303ec797a066ea5bc27266caa4402-32.png?1747916307"
[[feeds.feedlist]]
link = "https://disclose.ngo/feed/"
domain = "disclose.ngo"
title = "Disclose"
image = "https://disclose.ngo/assets/favicons/favicon.ico"
[[feeds.feedlist]]
link = "https://reporterre.net/spip.php?page=backend-simple"
domain = "reporterre.net"
title = "Reporterre"
image = "https://reporterre.net/squelettes/images/android-chrome-512x512.png"
[[feeds.feedlist]]
link = "https://www.alternatives-economiques.fr/rss.xml"
domain = "alternatives-economiques.fr"
title = "AlterÉco"
image = "https://www.alternatives-economiques.fr/sites/all/themes/alternatives-economiques-main/assets/apple-touch-icon.png"
[[feeds.feedlist]]
link = "https://rapportsdeforce.fr/feed"
domain = "rapportsdeforce.fr"
title = "Rapports de force"
image = "https://rapportsdeforce.fr/wp-content/themes/flymag-child/images/favicon-196x196.png"
[[feeds.feedlist]]
title = "L214"
image = "https://www.l214.com/wp-content/uploads/2020/02/Favicon-L214-64x64-1.png"
link = "https://www.l214.com/feed/"
domain = "l214.com"
[[feeds.feedlist]]
title = "L'Amorce"
image = "https://cdn.bsky.app/img/avatar/plain/did:plc:4ig26oattbxt5gepdy2yngec/bafkreigikxkg6dwpv55jmuvlsqxc4szfecbohnrydenb6m5dqxi52vwv7i"
link = "https://lamorce.co/feed/"
domain = "lamorce.co"
[[feeds.feedlist]]
title = "Oxfam France"
image = "https://www.oxfamfrance.org/app/uploads/2019/04/favicon-256x256.png"
link = "https://www.oxfamfrance.org/feed/"
domain = "oxfamfrance.org"
[[feeds.feedlist]]
title = "Attac"
image = "https://france.attac.org/favicon.ico"
link = "https://france.attac.org/spip.php?page=backend"
domain = "france.attac.org"
[[feeds.feedlist]]
title = "#AuPoste"
link = "https://www.auposte.fr/feed/"
domain = "auposte.fr"
image = "https://www.auposte.fr/wp-content/uploads/2022/10/cropped-Fichier-107@33.33x-1-1-32x32.png"
[[feeds.feedlist]]
title = "Off Investigation"
link = "https://www.off-investigation.fr/feed/"
domain = "off-investigation.fr"
image = "https://www.off-investigation.fr/wp-content/uploads/2021/05/favicon2.png"
# [[feeds.feedlist]]
# title = "Observatoire des multinationales"
# link = "https://multinationales.org/fr/page/backend"
# domain = "multinationales.org"
# image = "https://multinationales.org/squelettes/odm/static/img/favicon/android-chrome-192x192.png"
[[feeds.feedlist]]
title = "Bondy Blog"
link = "https://www.bondyblog.fr/feed/"
domain = "bondyblog.fr"
image = "https://www.bondyblog.fr/app/uploads/2020/10/cropped-LEBB-Rouge-192x192.png"
[[feeds.feedlist]]
title = "Histoires Crépues"
link = "https://histoirescrepues.fr/latest/rss/"
domain = "histoirescrepues.fr"
image = "https://histoirescrepues.fr/content/images/size/w256h256/2024/11/Plan-de-travail-2-copie.png"
[[feeds.feedlist]]
title = "INDEX"
link = "https://www.index.ngo/rubrique/enquetes/feed/"
domain = "index.ngo"
image = "https://www.index.ngo/wp-content/uploads/2023/05/cropped-INDEX-logo-square-black-white-192x192.jpg"
[[feeds.feedlist]]
title = "La Quadrature du Net"
link = "https://www.laquadrature.net/feed/"
domain = "laquadrature.net"
image = "https://www.laquadrature.net/wp-content/uploads/sites/8/2018/09/LOGO-LQDN3-36x36.png"
[[feeds.feedlist]]
title = "Le Mouton Numérique"
link = "https://mouton-numerique.org/feed/"
domain = "mouton-numerique.org"
image = "https://mouton-numerique.org/wp-content/uploads/2022/01/cropped-favicon-mouton-numerique-32x32.png"
[[feeds.feedlist]]
title = "Le Vent Se Lève"
link = "https://lvsl.fr/feed/"
domain = "lvsl.fr"
image = "https://lvsl.fr/wp-content/uploads/fbrfg/favicon.ico"
[[feeds.feedlist]]
title = "La Déferlante"
link = "https://revueladeferlante.fr/feed/"
domain = "revueladeferlante.fr"
image = "https://694359d6.delivery.rocketcdn.me/wp-content/uploads/2021/01/cropped-ld_favicon2-2-300x300.png"
[[feeds.feedlist]]
title = "La Brèche"
link = "https://journal-labreche.fr/feed/"
domain = "journal-labreche.fr"
image = "https://journal-labreche.fr/ezessogn/2025/05/cropped-Logo-RS-1-192x192.webp"
[[feeds.feedlist]]
title = "Synth."
link = "https://synthmedia.fr/feed/"
domain = "synthmedia.fr"
image = "https://synthmedia.fr/wp-content/uploads/2023/11/cropped-Synth-favicon-192x192.png"
[[feeds.feedlist]]
title = "STUP.MEDIA"
link = "https://stup.media/feed/"
domain = "stup.media"
image = "https://i0.wp.com/stup.media/wp-content/uploads/2024/03/cropped-cropped-ROND.png"
